app/src/Entity/TransactionsReport.php
<?php

namespace App\Entity;

use App\Repository\TransactionsReportRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TransactionsReportRepository::class)]
class TransactionsReport
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $file_name;

    #[ORM\Column(type: 'date')]
    private $report_date;

    #[ORM\Column(type: 'datetime')]
    private $created_at;

    #[ORM\Column(type: 'integer', nullable: true)]
    private $file_size;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileName(): ?string
    {
        return $this->file_name;
    }

    public function setFileName(string $file_name): self
    {
        $this->file_name = $file_name;

        return $this;
    }

    public function getReportDate(): ?\DateTimeInterface
    {
        return $this->report_date;
    }

    public function setReportDate(\DateTimeInterface $report_date): self
    {
        $this->report_date = $report_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getFileSize(): ?int
    {
        return $this->file_size;
    }

    public function setFileSize(?int $file_size): self
    {
        $this->file_size = $file_size;

        return $this;
    }
}

app/src/Controller/DashboardController.php
<?php
namespace App\Controller;

use App\Entity\TransactionsReport;
use App\Repository\TransactionsReportRepository;
use App\Form\Type\TransactionsReportType;
use App\Service\ReportFileReader;
use App\Service\FileUploader;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

class DashboardController extends AbstractController
{
    /**
     * @Route("/dashboard", name="dashboard_index")
     */
    public function index(
        Request $request, 
        ManagerRegistry $doctrine,
        TransactionsReportRepository $reportsReporitory,
        ReportFileReader $reportReader,
        FileUploader $fileUploader
    ): Response
    {
        $report = new TransactionsReport();
        $reports = $reportsReporitory->findAll();
        
        $form = $this->createForm(TransactionsReportType::class, $report);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reportFile = $form->get('file')->getData();

            if($reportFile){
                $reportFileSize = $reportFile->getSize();
                $reportFileName = $fileUploader->upload($reportFile);       

                // Process report file
                $reportReader->readReportFile($fileUploader->getFileFullPath());
                $reportTransactions = $reportReader->getReportTransactions();
                $reportTransactionsCount = count($reportTransactions);
                $currentReportDate = $reportReader->getReportDate();
                
                // Report validation
                $reportHasTransactions = true === $reportTransactionsCount > 0;
                $transactionDateExistsInDb = $reportsReporitory->checkIfReportDateExists($reportReader->getReportDate());
                
                if($reportHasTransactions && !$transactionDateExistsInDb)
                {
                    $entityManager = $doctrine->getManager();

                    // Persist report to DB
                    $report
                        ->setFileName($reportFileName)
                        ->setFileSize($reportFileSize)
                        ->setReportDate($currentReportDate)
                        ->setCreatedAt(new \DateTime());

                    $entityManager->persist($report);

                    // Batch insert Transactions from report to DB
                    // To do: Can be improved
                    $batchSize = 20;
                    for ($i = 1; $i < $reportTransactionsCount; ++$i) {
                        $entityManager->persist($reportTransactions[$i]);
                        if (($i % $batchSize) === 0) {
                            $entityManager->flush();
                            $entityManager->clear();
                        }
                    }

                    $entityManager->flush();

                    return $this->redirectToRoute('dashboard_index', ['success' => 1]); 
                }
                else {
                    $this->addFlash(
                        "error",
                        "Transações com a data de \"{$currentReportDate->format("Y-m-d")}\" já foram importadas previamente."
                    );
                }
                               
            }
        }

        return $this->renderForm('dashboard/index.html.twig', [
            'form' => $form,
            'reports' => $reports,
        ]);
        
    }
}

app/templates/dashboard/index.html.twig
{% extends "base.html.twig" %}
{% block title %}Dashboard{% endblock %}
{% block body %}
<header class="navbar navbar-expand-md navbar-dark bg-dark">
    <nav class="container-xxl flex-wrap flex-md-nowrap" aria-label="Main navigation">
        <a class="navbar-brand" href="#">
            App
        </a>
    </nav>
</header>
<div class="container-xxl my-md-4">
    <main>
        <section>
            <header>
                <h1>Importar transações</h1>
            </header>
            <div>
                {% if app.request.get("success") == 1 %}
                    <div class="alert alert-success" role="alert">
                        Arquivo importado com sucesso.        
                    </div>
                {% endif %}
                {% for messages in app.flashes(['error']) %}
                    {% for message in messages %}
                        <div class="alert alert-danger" role="alert">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endfor %}
                
                {{ form(form) }}
            </div>
        </section>

        <section>
            <header>
                <h1>Relatório de importações</h1>
            </header>
            <div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Arquivo</th>
                            <th scope="col">Tamanho (bytes)</th>
                            <th scope="col">Data transações</th>
                            <th scope="col">Data importação</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for report in reports %}
                            <tr>
                                <td>{{ report.id }}</td>
                                <td>{{ report.fileName }}</td>
                                <td>{{ report.fileSize }}</td>
                                <td>{{ report.reportDate|date('Y-m-d') }}</td>
                                <td>{{ report.createdAt|date('Y-m-d H:i:s') }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </section>
    </main>
</div>
{% endblock %}